In [1]:
from google.colab import files

uploaded = files.upload()

Saving coretech_clients_cleaned.csv to coretech_clients_cleaned.csv

In [2]:
import pandas as pd
import sqlite3

In [3]:
df = pd.read_csv("coretech_clients_cleaned.csv")

df.head()

,client_id,client_name,company_name,service,project_budget,project_duration_days,client_city,lead_source,status,rating
0,1,Ali Khan,ABC Tech,Web Development,5000,30,Lahore,Facebook,Completed,4.5
1,2,Sara Ahmed,Digital Hub,AI Solutions,7000,45,Karachi,Website,Active,4.8
2,3,Usman Malik,TechNova,Data Science,6500,40,Islamabad,LinkedIn,Completed,4.6
3,4,Ayesha Noor,SoftVision,Cloud Computing,8000,60,Lahore,Referral,Active,4.7
4,5,Hamza Ali,FutureTech,Mobile App,5500,35,Faisalabad,Facebook,Completed,4.3

In [4]:
connection = sqlite3.connect("coretech_clients.db")

cursor = connection.cursor()

print("Database Created")

Database Created

In [5]:
create_table = """

CREATE TABLE IF NOT EXISTS clients(

client_id INTEGER,
client_name TEXT,
company_name TEXT,
service TEXT,
project_budget INTEGER,
project_duration_days INTEGER,
client_city TEXT,
lead_source TEXT,
status TEXT,
rating REAL

)

"""

cursor.execute(create_table)

connection.commit()

print("Table Created")

Table Created

In [6]:
df.to_sql(
    "clients",
    connection,
    if_exists="append",
    index=False
)

print("Data Inserted")

Data Inserted

In [7]:
query = """
SELECT * FROM clients;
"""

result = pd.read_sql(query, connection)

result

,client_id,client_name,company_name,service,project_budget,project_duration_days,client_city,lead_source,status,rating
0,1,Ali Khan,ABC Tech,Web Development,5000,30,Lahore,Facebook,Completed,4.5
1,2,Sara Ahmed,Digital Hub,AI Solutions,7000,45,Karachi,Website,Active,4.8
2,3,Usman Malik,TechNova,Data Science,6500,40,Islamabad,LinkedIn,Completed,4.6
3,4,Ayesha Noor,SoftVision,Cloud Computing,8000,60,Lahore,Referral,Active,4.7
4,5,Hamza Ali,FutureTech,Mobile App,5500,35,Faisalabad,Facebook,Completed,4.3
5,6,Fatima Khan,SkyNet,Web Development,4500,25,Multan,Website,Active,4.4
6,7,Bilal Ahmed,NextGen,AI Solutions,9000,70,Karachi,LinkedIn,Completed,4.9
7,8,Zain Malik,TechFlow,Data Science,6200,38,Lahore,Referral,Completed,4.2
8,9,Mariam Noor,AlphaSoft,Cloud Computing,8500,65,Islamabad,Website,Active,4.8
9,10,Ahmed Raza,InnovateX,Mobile App,5300,32,Peshawar,Facebook,Completed,4.1
10,11,Hira Khan,Core Digital,Web Development,4800,28,Lahore,Referral,Active,4.5
11,12,Saad Ali,TechWorks,AI Solutions,7600,50,Karachi,Website,Completed,4.7
12,13,Amna Tariq,DataEdge,Data Science,6100,36,Multan,LinkedIn,Active,4.3
13,14,Farhan Malik,Vision Tech,Cloud Computing,9200,75,Islamabad,Facebook,Completed,4.9
14,15,Iqra Noor,Code Masters,Mobile App,5700,34,Lahore,Referral,Active,4.4
15,16,Talha Khan,SmartSoft,Web Development,5100,31,Karachi,Website,Completed,4.6
16,17,Sana Ahmed,TechBridge,AI Solutions,8400,58,Faisalabad,LinkedIn,Active,4.8
17,18,Adnan Ali,Future Systems,Data Science,6300,39,Lahore,Facebook,Completed,4.5
18,19,Areeba Khan,CloudNet,Cloud Computing,8800,68,Multan,Referral,Active,4.7
19,20,Shayan Malik,AppSphere,Mobile App,5900,37,Islamabad,Website,Completed,4.2
20,21,Noor Fatima,BrightTech,Web Development,5200,30,Karachi,LinkedIn,Active,4.5
21,22,Danish Ahmed,InfoSoft,AI Solutions,7900,52,Lahore,Facebook,Completed,4.6
22,23,Laiba Khan,SmartData,Data Science,6400,41,Peshawar,Referral,Active,4.4
23,24,Hassan Ali,CloudX,Cloud Computing,9300,80,Islamabad,Website,Completed,4.9
24,25,Mehwish Noor,AppTech,Mobile App,5600,33,Karachi,Facebook,Active,4.3
25,26,Jawad Khan,TechZone,Web Development,4900,29,Multan,LinkedIn,Completed,4.5
26,27,Kiran Ahmed,Apex Solutions,AI Solutions,8200,56,Lahore,Referral,Active,4.8
27,28,Umer Malik,DataWorks,Data Science,6700,42,Faisalabad,Website,Completed,4.6
28,29,Nida Fatima,CloudPro,Cloud Computing,8700,67,Karachi,Facebook,Active,4.7
29,30,Rehan Ali,MobileSoft,Mobile App,6000,40,Lahore,LinkedIn,Completed,4.4

In [8]:
query = """

SELECT *
FROM clients
WHERE client_city='Lahore';

"""

pd.read_sql(query, connection)

,client_id,client_name,company_name,service,project_budget,project_duration_days,client_city,lead_source,status,rating
0,1,Ali Khan,ABC Tech,Web Development,5000,30,Lahore,Facebook,Completed,4.5
1,4,Ayesha Noor,SoftVision,Cloud Computing,8000,60,Lahore,Referral,Active,4.7
2,8,Zain Malik,TechFlow,Data Science,6200,38,Lahore,Referral,Completed,4.2
3,11,Hira Khan,Core Digital,Web Development,4800,28,Lahore,Referral,Active,4.5
4,15,Iqra Noor,Code Masters,Mobile App,5700,34,Lahore,Referral,Active,4.4
5,18,Adnan Ali,Future Systems,Data Science,6300,39,Lahore,Facebook,Completed,4.5
6,22,Danish Ahmed,InfoSoft,AI Solutions,7900,52,Lahore,Facebook,Completed,4.6
7,27,Kiran Ahmed,Apex Solutions,AI Solutions,8200,56,Lahore,Referral,Active,4.8
8,30,Rehan Ali,MobileSoft,Mobile App,6000,40,Lahore,LinkedIn,Completed,4.4

In [9]:
query = """

SELECT client_name, service, status
FROM clients
WHERE status='Completed';

"""

pd.read_sql(query, connection)

     client_name          service     status
0       Ali Khan  Web Development  Completed
1    Usman Malik     Data Science  Completed
2      Hamza Ali       Mobile App  Completed
3    Bilal Ahmed     AI Solutions  Completed
4     Zain Malik     Data Science  Completed
5     Ahmed Raza       Mobile App  Completed
6       Saad Ali     AI Solutions  Completed
7   Farhan Malik  Cloud Computing  Completed
8     Talha Khan  Web Development  Completed
9      Adnan Ali     Data Science  Completed
10  Shayan Malik       Mobile App  Completed
11  Danish Ahmed     AI Solutions  Completed
12    Hassan Ali  Cloud Computing  Completed
13    Jawad Khan  Web Development  Completed
14    Umer Malik     Data Science  Completed
15     Rehan Ali       Mobile App  Completed

In [10]:
query = """

SELECT service,
COUNT(*) AS total_clients
FROM clients
GROUP BY service;

"""

pd.read_sql(query, connection)

           service  total_clients
0     AI Solutions              6
1  Cloud Computing              6
2     Data Science              6
3       Mobile App              6
4  Web Development              6

In [11]:
query = """

SELECT AVG(project_budget)
AS average_budget
FROM clients;

"""

pd.read_sql(query, connection)

   average_budget
0     6743.333333

In [12]:
query = """

SELECT *
FROM clients
ORDER BY project_budget DESC
LIMIT 1;

"""

pd.read_sql(query, connection)

,client_id,client_name,company_name,service,project_budget,project_duration_days,client_city,lead_source,status,rating
0,24,Hassan Ali,CloudX,Cloud Computing,9300,80,Islamabad,Website,Completed,4.9

In [13]:
query = """

SELECT *
FROM clients
ORDER BY project_budget ASC
LIMIT 1;

"""

pd.read_sql(query, connection)

,client_id,client_name,company_name,service,project_budget,project_duration_days,client_city,lead_source,status,rating
0,6,Fatima Khan,SkyNet,Web Development,4500,25,Multan,Website,Active,4.4

In [14]:
query = """

SELECT client_name, rating
FROM clients
WHERE rating > 4;

"""

pd.read_sql(query, connection)

     client_name  rating
0       Ali Khan     4.5
1     Sara Ahmed     4.8
2    Usman Malik     4.6
3    Ayesha Noor     4.7
4      Hamza Ali     4.3
5    Fatima Khan     4.4
6    Bilal Ahmed     4.9
7     Zain Malik     4.2
8    Mariam Noor     4.8
9     Ahmed Raza     4.1
10     Hira Khan     4.5
11      Saad Ali     4.7
12    Amna Tariq     4.3
13  Farhan Malik     4.9
14     Iqra Noor     4.4
15    Talha Khan     4.6
16    Sana Ahmed     4.8
17     Adnan Ali     4.5
18   Areeba Khan     4.7
19  Shayan Malik     4.2
20   Noor Fatima     4.5
21  Danish Ahmed     4.6
22    Laiba Khan     4.4
23    Hassan Ali     4.9
24  Mehwish Noor     4.3
25    Jawad Khan     4.5
26   Kiran Ahmed     4.8
27    Umer Malik     4.6
28   Nida Fatima     4.7
29     Rehan Ali     4.4

In [15]:
query = """

SELECT status,
COUNT(*) AS total
FROM clients
GROUP BY status;

"""

pd.read_sql(query, connection)

      status  total
0     Active     14
1  Completed     16

In [16]:
query = """

SELECT client_name,
company_name,
project_budget
FROM clients
ORDER BY project_budget DESC
LIMIT 5;

"""

pd.read_sql(query, connection)

    client_name company_name  project_budget
0    Hassan Ali       CloudX            9300
1  Farhan Malik  Vision Tech            9200
2   Bilal Ahmed      NextGen            9000
3   Areeba Khan     CloudNet            8800
4   Nida Fatima     CloudPro            8700

In [17]:
connection.close()

print("Database Closed")

Database Closed